check_plate:
  name: Check Plate
  description: Check if a license plate is valid using the CampingCare API.
  fields:
    plate:
      name: License Plate
      description: License plate to look up.
      required: true
      example: AB123CD
      selector:
        text:

query_plate:
  name: Query Plate
  description: Query the CampingCare API with a license plate and retrieve reservation details
  fields:
    plate:
      name: License Plate
      description: License plate to look up.
      required: true
      example: AB123CD
      selector:
        text:
    start_date:
      name: Start Date
      description: The start date for the query (optional).
      required: false
      example: 2025-01-01
      selector:
      text:
    end_date:
      name: End Date
      description: The end date for the query (optional).
      required: false
      example: 2025-01-10
      selector:
      text:

get_reservation:
  name: Get Reservation
  description: Retrieve reservation details using the CampingCare API.
  fields:
    reservation_id:
      name: Reservation ID
      description: The ID of the reservation to retrieve.
      required: true
      example: 12345
      selector:
        text: